volumes:
  mongodbdata:
  filedata:

services:
  gateway:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  tunnel:
    image: ngrok/ngrok:latest
    container_name: tunnel
    command: "http gateway:80 --domain=${NGROK_DOMAIN}"
    env_file:
      - ./.env
    depends_on:
      - gateway

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.env
    volumes:
      - mongodbdata:/data/db

  server:
    image: imageboard:latest
    container_name: server
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/imageboard
      - STORAGE_DRIVER=node_local
      - STORAGE_BASE_PATH=/home/node
    command: npm run nx run @internal/server:start
    volumes:
      - filedata:/home/node

  client:
    image: imageboard:latest
    container_name: client
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    command: npm run nx run @internal/client:start
