services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.env

  server:
    image: jackbooru:latest
    container_name: jackbooru_server
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/imageboard
    command: npm run nx run @internal/server:start

  client:
    image: jackbooru:latest
    container_name: jackbooru_client
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    command: npm run nx run @internal/client:start
