/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExploreIndexImport } from './routes/explore/index'
import { Route as ExploreSingleImport } from './routes/explore/single'

// Create Virtual Routes

const ExploreLazyImport = createFileRoute('/explore')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ExploreLazyRoute = ExploreLazyImport.update({
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/explore.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ExploreIndexRoute = ExploreIndexImport.update({
  path: '/',
  getParentRoute: () => ExploreLazyRoute,
} as any)

const ExploreSingleRoute = ExploreSingleImport.update({
  path: '/single',
  getParentRoute: () => ExploreLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreLazyImport
      parentRoute: typeof rootRoute
    }
    '/explore/single': {
      id: '/explore/single'
      path: '/single'
      fullPath: '/explore/single'
      preLoaderRoute: typeof ExploreSingleImport
      parentRoute: typeof ExploreLazyImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexImport
      parentRoute: typeof ExploreLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ExploreLazyRoute: ExploreLazyRoute.addChildren({
    ExploreSingleRoute,
    ExploreIndexRoute,
  }),
})

/* prettier-ignore-end */
