import type { CodegenConfig } from "@graphql-codegen/cli";

const generatedComment = `/* eslint-disable */
// @ts-nocheck

/**
 * ⚠️ THIS FILE HAS BEEN GENERATED BY A CODE GENERATOR.
 *
 * YOU SHOULD NOT MAKE CHANGES TO THIS FILE.
 */
`;

export default {
  schema: "./src/typedefs.graphql",
  generates: {
    "./src/types/generated-graphql-types.ts": {
      plugins: ["typescript", "typescript-resolvers", { add: { content: generatedComment } }],
      config: {
        useIndexSignature: true,
        contextType: "./src/types/graphql-context.ts#GqlContext",
        enumsAsTypes: true
      }
    }
  }
} satisfies CodegenConfig;
