import type { CodegenConfig } from "@graphql-codegen/cli";

// As you're viewing the config, ignore the below message
const generatedComment = `/* eslint-disable */

/**
 * ⚠️ THIS FILE HAS BEEN GENERATED BY A CODE GENERATOR.
 *
 * YOU SHOULD NOT MAKE CHANGES TO THIS FILE.
 */
`;

export default {
  schema: "./src/typedefs.graphql",
  generates: {
    "./src/types/generated-graphql-types.ts": {
      plugins: ["typescript", "typescript-resolvers", { add: { content: generatedComment } }],
      config: {
        useIndexSignature: true,
        contextType: "./graphql-context.js#GqlContext",
        enumsAsTypes: true // Avoids generating TS enums (and prefers string union) for compatibility with drizzle pg enums, also string unions are preferred anyway
      }
    }
  }
} satisfies CodegenConfig;
