import type { CodegenConfig } from "@graphql-codegen/cli";

const generatedComment = `/* eslint-disable */
// @ts-nocheck

/**
 * ⚠️ THIS FILE HAS BEEN GENERATED BY A CODE GENERATOR.
 *
 * YOU SHOULD NOT MAKE CHANGES TO THIS FILE.
 */
`;

export default {
  overwrite: true,
  schema: [{ "my-api": { loader: "./src/introspect-apollo-server.ts" } }],
  documents: "src/graphql/*-{query,mutation,fragment}.graphql",
  emitLegacyCommonJSImports: false,
  generates: {
    "src/hooks/generated-graphql-hooks.tsx": {
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-react-apollo",
        { add: { content: generatedComment } }
      ],
      config: {
        withComponent: true,
        useTypeImports: true,
        possibleTypes: true
      }
    }
  }
} satisfies CodegenConfig;
